app_name = "progress_billing"
app_title = "Progress Billing"
app_publisher = "Globcom Qatar"
app_description = "Percentage-of-contract-value progress invoicing for ERPNext Sales Orders"
app_email = "waheed@globcomqatar.com"
app_license = "mit"
